### ISSUE TITLE
Zoom in rotated 90deg video in WebRTC

### ISSUE THREAD

**Issue by Smosia** [dbuezas/pan-zoom-controller#1]
Hello.
First of all, thank you for digital ptz for webRTC component.

I found that your code conficts with css video rotation in webRTC component.
AlexxIT webRTC component has ability to rotate 90 deg video using css command:
`style: 'video {transform: rotate(90deg); aspect-ratio: 1}'`

If digital ptz enabled, rotation of video doesn't work anymore.
But if I disable digital ptz using:
`digital_ptz: false`
everything works good.

Maybe you can add an option in config that would swap videoWidth and videoHeight in your script?
Or there is another way to fix that problem.
Thank you

P.S. I've opened issue here because you are developer of that functionality and also have repo for that controller. I can open same issue in AlexxIT repo, if that would be better.

**Comment by dbuezas** [comment]
Hi,
I hadn't thought about that.
I think it's better if you open an issue in the webrtc repo and we can all think what could be a good solution.

I'd have to think a bit more, but it may be possible to apply the digital ptz transformations after the user's custom transform and have everything still in working order.
